//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSOT_Praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int ID_Course { get; set; }
        public int ID_Group { get; set; }
        public int ID_Training_program { get; set; }
        public string ID_Worler { get; set; }
        public int ID_Teacher { get; set; }
    
        public virtual TrainingProgram TrainingProgram { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
