//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSOT_Praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LearningProgram()
        {
            this.TrainingProgram = new HashSet<TrainingProgram>();
        }
    
        public int ID_LearningProgram { get; set; }
        public string Name { get; set; }
        public int KeyOfProgram { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingProgram> TrainingProgram { get; set; }
    }
}
