//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSOT_Praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationCertificates
    {
        public int IdCertificate { get; set; }
        public string ProtocolNumber { get; set; }
        public int IdWorker { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string Code { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
