//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSOT_Praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID_Student { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Post { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Education { get; set; }
        public int Number_of_certificate { get; set; }
        public int ID_Training_program { get; set; }
        public int ID_Firm { get; set; }
        public byte[] Student_photo { get; set; }
    
        public virtual Education Education1 { get; set; }
        public virtual Firm Firm { get; set; }
        public virtual TrainingProgram TrainingProgram { get; set; }
    }
}
