//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSOT_Praktika.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxlastname {
            get {
                return ((string)(this["TextBoxlastname"]));
            }
            set {
                this["TextBoxlastname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxfirstname {
            get {
                return ((string)(this["TextBoxfirstname"]));
            }
            set {
                this["TextBoxfirstname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxmiddlename {
            get {
                return ((string)(this["TextBoxmiddlename"]));
            }
            set {
                this["TextBoxmiddlename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime datepickerbirthday {
            get {
                return ((global::System.DateTime)(this["datepickerbirthday"]));
            }
            set {
                this["datepickerbirthday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxlistfirm {
            get {
                return ((int)(this["ComboBoxlistfirm"]));
            }
            set {
                this["ComboBoxlistfirm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxposition {
            get {
                return ((string)(this["TextBoxposition"]));
            }
            set {
                this["TextBoxposition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxlisteducation {
            get {
                return ((int)(this["ComboBoxlisteducation"]));
            }
            set {
                this["ComboBoxlisteducation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxnumberdiploma {
            get {
                return ((string)(this["TextBoxnumberdiploma"]));
            }
            set {
                this["TextBoxnumberdiploma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DatePickerBeginLearning {
            get {
                return ((global::System.DateTime)(this["DatePickerBeginLearning"]));
            }
            set {
                this["DatePickerBeginLearning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DatePickerEndLearning {
            get {
                return ((global::System.DateTime)(this["DatePickerEndLearning"]));
            }
            set {
                this["DatePickerEndLearning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxNumberSertificate {
            get {
                return ((string)(this["TextBoxNumberSertificate"]));
            }
            set {
                this["TextBoxNumberSertificate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxListLearningProgram {
            get {
                return ((int)(this["ComboBoxListLearningProgram"]));
            }
            set {
                this["ComboBoxListLearningProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxYearLearning {
            get {
                return ((string)(this["TextBoxYearLearning"]));
            }
            set {
                this["TextBoxYearLearning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxNumberGroup {
            get {
                return ((string)(this["TextBoxNumberGroup"]));
            }
            set {
                this["TextBoxNumberGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextBoxStudyProgram {
            get {
                return ((string)(this["TextBoxStudyProgram"]));
            }
            set {
                this["TextBoxStudyProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DatePickerDateFilling {
            get {
                return ((global::System.DateTime)(this["DatePickerDateFilling"]));
            }
            set {
                this["DatePickerDateFilling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComboBoxListWorker {
            get {
                return ((int)(this["ComboBoxListWorker"]));
            }
            set {
                this["ComboBoxListWorker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ID1 {
            get {
                return ((int)(this["ID1"]));
            }
            set {
                this["ID1"] = value;
            }
        }
    }
}
